// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gender.proto

package com.ieslab.protobuf;

public final class GenderProto {
  private GenderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.ieslab.protobuf.GenderType}
   */
  public enum GenderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Female = 0;</code>
     */
    Female(0, 0),
    /**
     * <code>Male = 1;</code>
     */
    Male(1, 1),
    ;

    /**
     * <code>Female = 0;</code>
     */
    public static final int Female_VALUE = 0;
    /**
     * <code>Male = 1;</code>
     */
    public static final int Male_VALUE = 1;


    public final int getNumber() { return value; }

    public static GenderType valueOf(int value) {
      switch (value) {
        case 0: return Female;
        case 1: return Male;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GenderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GenderType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GenderType>() {
            public GenderType findValueByNumber(int number) {
              return GenderType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ieslab.protobuf.GenderProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final GenderType[] VALUES = values();

    public static GenderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GenderType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ieslab.protobuf.GenderType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014gender.proto\022\023com.ieslab.protobuf*\"\n\nG" +
      "enderType\022\n\n\006Female\020\000\022\010\n\004Male\020\001B\rB\013Gende" +
      "rProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
